@Library("mylibrary")_
node("built-in")
{
    stage('ContDownload_Master')
    {
        cicd.newgit("maven.git")
    }
    stage('ContBuild_Master')
    {
        cicd.newMaven()
    }
    stage('ContDeployment_Master')
    {
        cicd.newdeploy("ScriptedPipelinewithsharedlibraires","172.31.19.217","testapp")
    }
    stage('contTesting_Master')
    {
        cicd.newgit("FunctionalTesting")
        cicd.runselenium("ScriptedPipelinewithsharedlibraires")
    }
    stage('ContDelivery_Master')
    {
        cicd.newdeploy("ScriptedPipelinewithsharedlibraires","172.31.28.203","prodapp")
    }
}
